name: Pre-release to latest

on:
  push:
    branches:
      master

jobs:
  build:
    strategy:
      matrix:
        # we are building a pure python wheel so it should work on any platform
        os: [ubuntu-latest]
        python-versions: [3.7]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
      - name: Run unit tests
        run: python -m unittest
      - name: Flake8
        run: flake8
      - name: Autopep8
        run: autopep8 --in-place --aggressive --recursive machine_common_sense
      - name: create wheel file
        run: python setup.py bdist_wheel sdist clean --all
      - name: download unity packages
        run: echo download ${GITHUB_REF##*/} and save in dist
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          #Can set an automatic release tag or let it use the initial tag.  If latter, need to conform to semantic versioning.
          # Note, so far, we don't conform to semantic versioning.
          #alternatively, we could always tag as latest   
          automatic_release_tag: latest
          prerelease: true
          title: "Latest Pre-Release"
          files: |
            dist/*
