# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: 'machine_common_sense/|tests/|integration_tests/|webenabled/'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
    -   id: autopep8
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
-   repo: local
    hooks:
    -   id: sphinx
        name: sphinx
        entry: ./docs/generate_sphinx_docs.sh
        language: script
        verbose: true
