version: ""
neonServerUrl: ""
projectIcon: ""
projectTitle: "Evaluation Submissions"
lastModified: 1572378751950
fileName: "config.yaml"

datastores:
  es1:
    name: "es1"
    host: "neon-es"
    type: "elasticsearchrest"
    databases:
      msc_eval:
        name: "msc_eval"
        prettyName: "msc_eval"
        tables:
          eval1:
            name: "eval1"
            prettyName: "eval1"
            mappings: {}
            labelOptions: {}
            fields:
            - columnName: "performer"
              prettyName: "performer"
              hide: false
              type: "keyword"
            - columnName: "complexity"
              prettyName: "complexity"
              hide: false
              type: "keyword"
            - columnName: "test"
              prettyName: "test"
              hide: false
              type: "keyword"
            - columnName: "plausibility"
              prettyName: "plausibility"
              hide: false
              type: "double"
            - columnName: "ground_truth"
              prettyName: "ground_truth"
              hide: false
              type: "double"
            - columnName: "num_objects"
              prettyName: "num_objects"
              hide: false
              type: "keyword"
            - columnName: "block"
              prettyName: "block"
              hide: false
              type: "keyword"
            - columnName: "occluder"
              prettyName: "occluder"
              hide: false
              type: "keyword"
            - columnName: "scene"
              prettyName: "scene"
              hide: false
              type: "keyword"
            - columnName: "_id"
              prettyName: "_id"
              hide: false
              type: "text"


dashboards:
  layout: "evaluation_1"
  filters: []
  fields: {}
  tables:
    table_key_1: "es1.msc_eval.eval1"
  options:
    connectOnLoad: true
  visualizationTitles: {}
  contributors: {}
  fullTitle: "Evaluation 1"
  name: "Evaluation_1"


layouts:
  evaluation_1:
  
  - bindings:
      title: "Performer"
      type: "bar-v"
      _id: "7c6db303-93c7-4aa0-bc35-6a152f0befd3"
      xField: "performer"
    col: 1
    row: 1
    name: "Performer"
    sizex: 4
    sizey: 4
    type: "aggregation"
    
  - bindings:
      title: "Submission"
      type: "bar-v"
      _id: "7c6db303-93c7-4aa0-bc35-6a152f0befd3"
      xField: "submission"
    col: 5
    row: 1
    name: "Submission"
    sizex: 4
    sizey: 4
    type: "aggregation"
    
  - bindings:
      title: "Block"
      type: "bar-v"
      _id: "1e7c52f7-e9aa-4b02-8da8-4388a66806e0"
      xField: "block"
    col: 9
    row: 1
    name: "Block"
    sizex: 4
    sizey: 4
    type: "aggregation"

  - bindings:
      title: "Complexity"
      type: "bar-v"
      _id: "81eb0fc7-66c0-4d66-9f85-c32ceec24a93"
      xField: "complexity"
    col: 1
    row: 5
    name: "Complexity"
    sizex: 4
    sizey: 4
    type: "aggregation"

  - bindings:
      title: "NumObjects"
      type: "bar-v"
      _id: "03da6de8-ca87-4911-8609-75de2d3968b8"
      xField: "num_objects"
    col: 1
    row: 9
    name: "NumObjects"
    sizex: 4
    sizey: 4
    type: "aggregation"

  - bindings:
      title: "Occluder"
      type: "bar-v"
      _id: "03da6de8-ca87-4911-8609-75de2d3968b8"
      xField: "occluder"
    col: 1
    row: 13
    name: "Occluder"
    sizex: 4
    sizey: 4
    type: "aggregation"

  - bindings:
      title: "Ground Truth vs Plausibility"
      type: "scatter-xy"
      _id: "24886883-2c5f-481a-b766-57414e4666cf"
      xField: "ground_truth"
      yField: "plausibility"
      scaleMinX: "-0.1"
      scaleMaxX: "1.1"
    col: 5
    row: 5
    name: "Ground Truth vs Plausibility"
    sizex: 5
    sizey: 10
    type: "aggregation"

  - bindings:
      title: "Raw Data"
      tableKey: "table_key_1"
      idField: "_id_key"
      limit: 100
      ignoreSelf: false
      _id: "1cd9cb1f-81ed-4809-b949-57e01b07cd12"
      linkPrefix: "http://ec2-54-173-69-214.compute-1.amazonaws.com:3000/"
      linkFields:
      - url_string
      showFields:
      - performer
      - submission
      - block
      - test
      - scene
      - complexity
      - num_objects
      - occluder
      - ground_truth
      - plausibility
      - voe_signal
      - url_string
    col: 1
    row: 20
    name: "Data Table"
    sizex: 12
    sizey: 6
    type: "dataTable"

