name: Mac/Ubuntu Python 3.10 Unit Tests 

on:
  push:
    branches-ignore:
      - development
      - master
      - gh-pages

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
      - name: Run unit tests
        run: python -m unittest
      - name: Isort
        uses: isort/isort-action@v1.0.0
      - name: Flake8
        run: flake8
      - name: Autopep8
        run: autopep8 --in-place --aggressive --recursive machine_common_sense
